apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xafe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xafe
    app.kubernetes.io/part-of: ci1t-830-0068-app
  name: devfile-sample-xafe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xafe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xafe
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0068-tenant/ci1t-830-0068-app/devfile-sample-xafe@sha256:23da60617236882aa812fa673ad6c3d1ca780a19fa860fdc99c80af3e722d94a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
